_commit: v0.5.0
_src_path: https://github.com/gabriel-andreescu/BethesdaModKit.git
author: GabonZ
components:
- native
description: Stops lingering combat music.
devbench_api: false
devbench_tests: false
game: skyrim
mcm: false
native_settings: true
native_source: src
pack_assets: false
pre_commit: true
project_name: CombatMusicFixNG
tooling_only: false
