[CombatMusic]
; Toggle debug logging.
bDebugLogging=0

; Only stop music after loading a save.
bOnlyAtSaveLoad=0

; Comma-separated music types to stop when the player is out of combat.
StopTracks=MUScombat, MUScombatCivilWar, MUScombatBossUmbra, MUScombatBossDLC1, MUScombatBossChargen, MUScombatBoss, DLC2MUScombatKarstaag, DLC2MUScombatBoss
