name: Build and release

on:
  push:
    branches: [main]
    tags: ["v[0-9]*", "[0-9]*"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
    uses: gabriel-andreescu/BethesdaModKit/.github/workflows/build.yml@v0.5.0
    with:
      publish-nexus: true
    secrets:
      NEXUSMODS_API_KEY: ${{ secrets.NEXUSMODS_API_KEY }}
